Algoritmo "07 - multiplos"
// Disciplina   : [Linguagem e Lógica de Programação com VisualG]
// Professor    : Jailson
// Descrição    : Verifica se um número é múltiplo do outro
// Autor(a)     : Maria Luisa Mota
// Data atual   : 21/04/2026

Var
a, b: inteiro

Inicio

Escreval("Digite o primeiro número: ")
leia(a)

Escreval("Digite o segundo número: ")
leia(b)

se (a % b = 0) entao
   Escreval("O primeiro é múltiplo do segundo")
fimse

Fimalgoritmo