Algoritmo "5.09 - temperatura"
// Disciplina   : [Linguagem e Lógica de Programação com VisualG]
// Professor    : Jailson
// Descrição    : Verifica superaquecimento do hardware
// Autor(a)     : Maria Luisa Mota
// Data atual   : 21/04/2026

Var
temp: real

Inicio

Escreval("Digite a temperatura: ")
leia(temp)

se (temp > 75) entao
   Escreval("Alerta de superaquecimento de hardware")
fimse

Fimalgoritmo