Algoritmo "4.51 - senha"
// Disciplina   : [Linguagem e Lógica de Programação com VisualG]
// Professor   : Jailson
// Descrição   : Verifica se a senha está correta
// Autor(a)    : Maria Luisa Mota
// Data atual  : 21/04/2026

Var
// Seção de Declarações das variáveis
senha: inteiro

Inicio
// Seção de Comandos

Escreval("Digite a senha: ")
leia(senha)

se (senha = 1234) entao
   Escreval("ACESSO PERMITIDO")
senao
   Escreval("ACESSO NEGADO")
fimse

Fimalgoritmo