Algoritmo "4.53 - par_impar"
// Disciplina   : [Linguagem e Lógica de Programação com VisualG]
// Professor   : Jailson
// Descrição   : Verifica se o número é par ou ímpar
// Autor(a)    : Maria Luisa Mota
// Data atual  : 21/04/2026

Var
// Seção de Declarações das variáveis
num: inteiro

Inicio
// Seção de Comandos

Escreval("Digite um número inteiro: ")
leia(num)

se (num % 2 = 0) entao
   Escreval("Número PAR")
senao
   Escreval("Número ÍMPAR")
fimse

Fimalgoritmo