Algoritmo "5.16 - pacotes"
// Disciplina   : [Linguagem e Lógica de Programação com VisualG]
// Professor    : Jailson
// Descrição    : Verifica perda de pacotes
// Autor(a)     : Maria Luisa Mota
// Data atual   : 21/04/2026

Var
pacotes: inteiro

Inicio

Escreval("Digite a quantidade de pacotes perdidos: ")
leia(pacotes)

se (pacotes <> 0) entao
   Escreval("Transmissão com perdas")
senao
   Escreval("Transmissão perfeita")
fimse

Fimalgoritmo