Algoritmo "8.20 - celsius_fahrenheit"
// Disciplina   : [Linguagem e Lógica de Programação com VisualG]
// Professor    : Jailson
// Descrição    : Converte Celsius para Fahrenheit
// Autor(a)     : Maria Luisa Mota
// Data atual   : 21/04/2026

Var
c, f: real

Inicio

Escreval("Digite a temperatura em Celsius: ")
leia(c)

f <- (c * 9/5) + 32

Escreval("Temperatura em Fahrenheit: ", f:0:2)

Fimalgoritmo