Algoritmo "areaTriangulo"
// Disciplina  : [Linguagem e Lógica de Programação com VisualG]
// Professor   : Jailson
// Descrição   : Recebe dois valores,multiplica por eles, divide por 2 e exibe o resultado q seria o area do Triângulo
// Autor(a)    : Maria Luisa Mota Santos
// Data atual  : 20/03/2026
Var
// Seção de Declarações das variáveis
altura: real
base: real
resultado: real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc...
escreva ("Digite o valor do base: ")
leia (base)
escreva ("Digite o valor do altura: ")
leia (altura)
resultado <- (base * altura)/2
escreval ("o area do triangulo é: ", resultado)

Fimalgoritmo