Algoritmo "areaRetangulo"
// Disciplina  : [Linguagem e Lógica de Programação com VisualG]
// Professor   : Jailson
// Descrição   : Recebe dois valores,multiplica por 4 e exibe o resultado q seria o area do retangulo
// Autor(a)    : Maria Luisa Mota Santos
// Data atual  : 20/03/2026
Var
// Seção de Declarações das variáveis
lado: real
base: real
resultado: real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc...
escreva ("Digite o valor do base: ")
leia (base)
escreva ("Digite o valor do lado: ")
leia (lado)
resultado <- base * lado
escreval ("o area do retangulo é: ", resultado)

Fimalgoritmo