Algoritmo "Divisao"
// Disciplina  : [Lógica de Programação com VisualG]
// Professor   : Jailson
// Descrição   : Solicita dois numeros, dive e exibe o resultado
// Autor(a)    : Maria Luisa Mota Santos
// Data atual  : 19/03/2026
Var
// Seção de Declarações das variáveis 
numero:real
numero2:real
resultado:real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
escreval ("divisao")
escreva("Digite o primeiro numero: ")
leia (numero)
escreva("Digite o segundo numero: ")
leia (numero2)
resultado <- numero / numero2
escreval(numero, "/", numero2, "=", resultado)

Fimalgoritmo