Algoritmo "Exercicio23"
// Disciplina   : [Linguagem e Lógica de Programação com VisualG]
// Professor   : Jailson
// Descrição   : Solicita um valor, verifica e exibe se o valor é positivo ou negativo
// Autor(a)    : Maria Luisa Mota Santos
// Data atual  : 26/03/2026
Var
   // Seção de Declarações das variáveis
   numero:inteiro

Inicio
   // Seção de Comandos, procedimento, funções, operadores, etc...
   escreval("Validação: número positivo ou negativo")
   escreval("Informe um número: ")
   leia(numero)
   se (numero > -1) então
      escreval("O número informado é positivo")
   senão
      escreval("Número negativo")
      
      fimse

Fimalgoritmo