Algoritmo "metros em centímetros"
// Disciplina  : [Lógica de Programação com VisualG]
// Professor   : Jailson
// Descrição   : Solicita um valor em metros, o converte para centímetros e mostra o resultado
// Autor(a)    : Maria Luisa Mota Santos
// Data atual  : 23/03/2026
Var
// Seção de Declarações das variáveis
numero: real
metro: inteiro


Inicio
// Seção de Comandos, procedimento, funções, operadores, etc...
metro <- 100
escreval("Digite um valor em metros")
leia(numero)
escreva("Seu número convertido em centímetros equivale à:", numero*metro, " centímetros.")

Fimalgoritmo