Algoritmo "perimetroRetangulo"
// Disciplina  : [Linguagem e Lógica de Programação com VisualG]
// Professor   : Jailson
// Descrição   : Recebe dois valores,soma, multiplica por 2 e exibe o resultado q seria o perimetro do Retangulo
// Autor(a)    : Maria Luisa Mota Santos
// Data atual  : 20/03/2026
Var
// Seção de Declarações das variáveis
altura: real
base: real
resultado: real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc...
escreva ("Digite o valor do base: ")
leia (base)
escreva ("Digite o valor do altura: ")
leia (altura)
resultado <- 2* (altura + lado)
escreval ("o area do retangulo é: ", resultado)

Fimalgoritmo